"""Cyclic Markov chain data generator for the toy superposition experiment.

The paper (Section 2.2) builds the toy pretraining corpus as a mixture of sequences
generated by N cyclic Markov chains over a shared state space of size V. Each chain is a
deterministic 4-cycle, so it contributes exactly V unique sequences (one per start state);
each unique sequence is one "feature". With 3 chains and V=4 there are 12 features, which
must be superposed into the toy model's 4-dimensional residual stream.
"""

import itertools
from dataclasses import dataclass

import numpy as np
import torch
from jaxtyping import Int


def cyclic_permutations(n_states: int, n_chains: int) -> list[tuple[int, ...]]:
    """Return the first `n_chains` distinct cyclic orders over `n_states` states.

    A cyclic order (0, p1, ..., p_{V-1}) defines the deterministic transition
    0 -> p1 -> ... -> p_{V-1} -> 0. Enumeration is deterministic (lexicographic over the
    tail permutation), so chain identity is stable across runs.
    """
    tails = itertools.permutations(range(1, n_states))
    cycles: list[tuple[int, ...]] = [(0, *tail) for tail in itertools.islice(tails, n_chains)]
    if len(cycles) < n_chains:
        raise ValueError(
            f"Only {len(cycles)} distinct cycles exist over {n_states} states; "
            f"requested {n_chains}. Increase n_states or decrease n_chains."
        )
    return cycles


def next_state_table(cycle: tuple[int, ...]) -> list[int]:
    """Convert a cyclic order into a next-state lookup table indexed by current state."""
    table = [0] * len(cycle)
    for position, state in enumerate(cycle):
        table[state] = cycle[(position + 1) % len(cycle)]
    return table


@dataclass(frozen=True, kw_only=True)
class Feature:
    """One unique sequence: a chain walked deterministically from a start state."""

    chain_idx: int
    start_state: int
    tokens: tuple[int, ...]


def build_features(*, n_chains: int, n_states: int, seq_len: int) -> list[Feature]:
    """Enumerate all N = n_chains * n_states unique sequences of length seq_len."""
    features = []
    for chain_idx, cycle in enumerate(cyclic_permutations(n_states, n_chains)):
        table = next_state_table(cycle)
        for start_state in range(n_states):
            tokens = [start_state]
            for _ in range(seq_len - 1):
                tokens.append(table[tokens[-1]])
            features.append(
                Feature(chain_idx=chain_idx, start_state=start_state, tokens=tuple(tokens))
            )
    return features


def feature_weights(
    features: list[Feature], *, underrepresented_chain: int, ratio: float
) -> np.ndarray:
    """Sampling weights: underrepresented chain's features get `ratio` x the others' weight."""
    if not 0.0 <= ratio <= 1.0:
        raise ValueError(f"ratio must be in [0, 1], got {ratio}")
    weights = np.array([ratio if f.chain_idx == underrepresented_chain else 1.0 for f in features])
    total = weights.sum()
    if total == 0:
        raise ValueError("All-zero sampling weights: ratio=0 with a single chain corpus.")
    return weights / total


def sample_batch(
    features: list[Feature],
    weights: np.ndarray,
    *,
    batch_size: int,
    rng: np.random.Generator,
) -> Int[torch.Tensor, "batch seq"]:
    """Sample a training batch of token sequences according to the feature weights."""
    idx = rng.choice(len(features), size=batch_size, p=weights)
    return torch.tensor([features[i].tokens for i in idx], dtype=torch.long)
